apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: ENV_VARIABLE_NAME
      value: ENV_VARIABLE_VALUE
    - name: SECRET_ENV_VARIABLE_NAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: SECRET_KEY_NAME
